spring.application.name=CampusSync
spring.profiles.active=${ENV:dev}

# Firebase Configuration
# Place your service account json in src/main/resources and name it firebase-service-account.json
# Or specify the path here:
# firebase.config.path=firebase-service-account.json

# RabbitMQ Configuration
#spring.rabbitmq.host=localhost
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
# STOMP Relay Port (Default is 61613, distinct from AMQP 5672)
#app.relay.port=61613
